# Override the outfit name (file name for new outfits, in-game name for game outfits)
name: "Maskless White Leotard (Red and White)"

# Which character assets slot this outfit is for.
character_assets: 1

# Whether the outfit should be treated as a default outfit.
# The default outfit is used when changing character assets or
# if a character has an outfit equipped that no longer exists.
is_default: false